sources:
  - name: Stagging
    database: AIRBNB
    schema: Staging  
    tables:
      - name: listings
      - name: bookings
      - name: hosts

  - name: stripe
    tables:
      - name: payments